paths: 
/api/products:
get:
      summary: Obtener todos los productos.
      tags:
        - Products
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.
put:
 summary: Acts.
      tags:
        - Products
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.

/api/products/add:
post:
sumary: Agregar un nuevo producto.
      tags:
        - Products
        requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.

/api/products/{pid}:
get:
summary: Obtener producto con id dado por parametros.
      tags:
        - Products
      responses:
        "200":
          description: Producto encontrado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: No se encuentra producto con ese ID.
        "500":
          description: Error interno del servidor.

put:
summary: Modificar producto con in dado por parámetros.
      tags:
        - Products
      responses:
        "200":
          description: Producto actualizado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.

delete:
summary: Eliminar producto con ID dado.
      tags:
        - Products
      responses:
        "200":
          description: Producto eliminado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        "401":
          description: Error por falta de permisos.
        "500":
          description: Error interno del servidor.

components:
  schemas:
      Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id del producto.
        title:
          type: string
          description: Nombre del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: numbre
          description: Precio del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        code:
          type: string
          description: Código único del producto.
        stock:
          type: number
          description: Cantidad de producto disponible.
        owner:
          type: object
          description: Creador del producto.

      example:
    _id: ObjectId("gsa98273skjhgda8912")
    title: Camisa
    description: Azul oscura.
    price: 80
    thumbnail: "google.com/photos/camisas"
    code: "0258"
    stock: 25
    owner: ObjectId("gsa98273skjhkjhgsasd12")
  requestBodies:
    UpdateProduct:
         title:
          type: string
          description: Nombre del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: numbre
          description: Precio del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        code:
          type: string
          description: Código único del producto.
        stock:
          type: number
          description: Cantidad de producto disponible.
      example:
       title: Camisa
    description: Azul clara.
    price: 70
    thumbnail: Sin imagen.
    code: "0258"
    stock: 25